name: Open your eyes
description: Install Python requirements
runs:
  using: composite
  steps:
  - uses: actions/setup-python@v5
    with:
      python-version: '3.13'
      cache: pip
  - run: pip install -r requirements.txt
    shell: sh
